---
- hosts: 
#  - all
  - testing
  - produccion

  # Variables Globales
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI
   

    - include_role:
        name: alta_usuarios_antartida

    - include_role:
        name: Sudoers_antartida

    - name: "Crear directorio /tmp/Grupo"
      debug:
        msg: "Directorio Creado."

    - name: "Crear archivo datos.txt"
      debug:
        msg: "Archivo creado."


    - name: "Crear el grupo secundario"
      debug:
        msg: "Grupo secundario 'Antartida' creado."

    - name: "Creando grupos principales"
      debug:
        msg: "Grupos principales creados."


    - name: "Creando usuarios"
      debug:
        msg: "Usuarios creados."

    - name: "Agregar configuración sudoers para el grupo"
      debug:
        msg: "Grupo antartida con permiso de sudoers"
